name: "Build"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 19 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build & Test
        run: mvn clean verify

      - name: Archive Test Logs On Failure
        if: failure()
        run: tar -czvf surefire-reports-jdk-${{ matrix.java }}.tar.gz **/target/surefire-reports/*

      - name: Upload Test Logs On Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports-jdk-${{ matrix.java }}
          path: surefire-reports-jdk-${{ matrix.java }}.tar.gz

      - name: Javadoc etc
        run: mvn clean verify -Papache-release -Dgpg.skip -DskipTests

      - name: RAT check
        run: mvn clean -Papache-release apache-rat:check

